# Generated by Django 4.0.6 on 2022-07-30 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('evasion', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('spirit', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('evasion', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('spirit', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('experience', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('magical', models.BooleanField()),
                ('character', models.ManyToManyField(to='duelapp.character')),
            ],
        ),
    ]
